spring.datasource.url=${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:${DATABASE_URL:}}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USER:${PGUSER:}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:${PGPASSWORD:}}}

spring.datasource.hikari.data-source-properties.sslmode=${PGSSLMODE:require}
spring.datasource.hikari.data-source-properties.connectTimeout=${PG_CONNECT_TIMEOUT:10}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
