spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:file:./data/local-db;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:schema.sql,classpath:migrations/20260217_add_calendar_view_preference.sql
spring.sql.init.data-locations=classpath:data/*.sql

# Use local port unless overridden
server.port=${PORT:8080}

debug=true
logging.level.root=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.boot.devtools=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
logging.level.uk.ac.cf._5.group14=DEBUG