package uk.ac.cf._5.group14.One_To_One.Security;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class PrivilegedAuditServiceTest {

    private JdbcTemplate jdbcTemplate;
    private Clock clock;

    @BeforeEach
    void setUp() {
        jdbcTemplate = new JdbcTemplate(new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .generateUniqueName(true)
                .build());
        jdbcTemplate.execute("""
                CREATE TABLE privileged_audit_events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    request_id VARCHAR(80) NOT NULL,
                    actor VARCHAR(100) NOT NULL,
                    authorities VARCHAR(500) NOT NULL,
                    http_method VARCHAR(10) NOT NULL,
                    request_path VARCHAR(500) NOT NULL,
                    response_status INT NOT NULL,
                    succeeded BOOLEAN NOT NULL,
                    source_ip_hash CHAR(64) NOT NULL
                )
                """);
        clock = Clock.fixed(Instant.parse("2026-07-29T10:00:00Z"), ZoneOffset.UTC);
    }

    @Test
    void retainsOutcomeWithoutRawSourceAddressAndPurgesByPolicyCutoff() {
        PrivilegedAuditService service = new PrivilegedAuditService(jdbcTemplate, clock);

        service.record(
                "request-1",
                "operator",
                "ROLE_PLATFORM_ADMIN",
                "POST",
                "/admin/feedback/7/resolve",
                204,
                "192.0.2.44");

        Map<String, Object> row = jdbcTemplate.queryForMap("SELECT * FROM privileged_audit_events");
        assertThat(row.get("ACTOR")).isEqualTo("operator");
        assertThat(row.get("REQUEST_PATH")).isEqualTo("/admin/feedback/7/resolve");
        assertThat(row.get("SUCCEEDED")).isEqualTo(true);
        assertThat(row.get("SOURCE_IP_HASH").toString()).doesNotContain("192.0.2.44");

        assertThat(service.purgeBefore(Instant.parse("2026-07-29T10:00:01Z"))).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM privileged_audit_events",
                Integer.class)).isZero();
    }
}
