ALTER TABLE vault_notes ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE vault_notes ADD COLUMN IF NOT EXISTS tags VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE vault_notes ADD COLUMN IF NOT EXISTS mood VARCHAR(20) NULL;
ALTER TABLE vault_notes ADD COLUMN IF NOT EXISTS ai_summary TEXT NULL;
