-- Waitlist email sign-up table for dev mode notifications
-- This table is intentionally NOT listed in schema.sql DROP statements
-- so that sign-up data persists across application restarts.
CREATE TABLE IF NOT EXISTS waitlist_emails (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    signed_up_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed   BOOLEAN NOT NULL DEFAULT FALSE
);
