package uk.ac.cf._5.group14.One_To_One.PaymentCards;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class CardEncryptionKeyVerifierTest {

    private static final String KEY = key("phase4-primary-key");
    private static final String DIFFERENT_KEY = key("phase4-different-key");

    private EmbeddedDatabase database;
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        database = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .generateUniqueName(true)
                .build();
        jdbcTemplate = new JdbcTemplate(database);
        jdbcTemplate.execute("""
                CREATE TABLE card_encryption_key_checks (
                    id SMALLINT PRIMARY KEY,
                    encrypted_marker TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    verified_at TIMESTAMP WITH TIME ZONE NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE saved_payment_methods (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    provider_payment_method_id TEXT
                )
                """);
    }

    @Test
    void createsMarkerAndVerifiesSavedTokensAcrossControlledRestart() {
        CardEncryptionService first = encryptionService(KEY);
        new CardEncryptionKeyVerifier(jdbcTemplate, first, true).run(null);
        jdbcTemplate.update(
                "INSERT INTO saved_payment_methods (provider_payment_method_id) VALUES (?)",
                first.encrypt("pm_test_restart_4242")
        );

        CardEncryptionService afterRestart = encryptionService(KEY);
        new CardEncryptionKeyVerifier(jdbcTemplate, afterRestart, true).run(null);

        assertThat(jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM card_encryption_key_checks",
                Integer.class
        )).isEqualTo(1);
    }

    @Test
    void failsStartupWhenPersistentKeyChanges() {
        new CardEncryptionKeyVerifier(
                jdbcTemplate,
                encryptionService(KEY),
                true
        ).run(null);

        assertThatThrownBy(() -> new CardEncryptionKeyVerifier(
                jdbcTemplate,
                encryptionService(DIFFERENT_KEY),
                true
        ).run(null))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Card decryption failed");
    }

    private static CardEncryptionService encryptionService(String key) {
        return new CardEncryptionService(key, "2bd", false, true);
    }

    private static String key(String seed) {
        return Base64.getEncoder().encodeToString(
                Arrays.copyOf(seed.getBytes(StandardCharsets.UTF_8), 32)
        );
    }
}
