export const viewports = {
  desktop: { width: 1440, height: 1000 },
  tablet: { width: 1024, height: 900 },
  mobile: { width: 390, height: 844 },
};

export const standards = {
  "PAGE-001": {
    category: "page",
    severity: "critical",
    title: "Page responds successfully",
    expected: "The configured route returns an accepted HTTP status and does not fail to load.",
    fix: "Repair the route, controller, template, data dependency or server error that prevents a successful response.",
  },
  "PAGE-002": {
    category: "page",
    severity: "major",
    title: "Page has a useful title",
    expected: "The document title is present, descriptive and between 8 and 70 characters.",
    fix: "Set a concise page-specific title in the page metadata and retain the One To One brand name.",
  },
  "PAGE-003": {
    category: "page",
    severity: "major",
    title: "Page has one main landmark",
    expected: "Rendered application pages contain exactly one visible <main> landmark.",
    fix: "Wrap the primary page content in one <main> element and avoid nested or duplicate main landmarks.",
  },
  "PAGE-004": {
    category: "page",
    severity: "major",
    title: "Page has one clear H1",
    expected: "Each page contains exactly one visible, non-empty H1 describing its purpose.",
    fix: "Add one page-level H1, or demote additional H1 elements to the appropriate heading level.",
  },
  "PAGE-005": {
    category: "page",
    severity: "minor",
    title: "Public page has search metadata",
    expected: "Public marketing pages provide a useful meta description between 50 and 170 characters.",
    fix: "Add a page-specific meta description that accurately summarises the page in natural British English.",
  },
  "PAGE-006": {
    category: "page",
    severity: "critical",
    title: "Authenticated page retains the profile session",
    expected: "A signed-in profile reaches the requested route without being returned to login or another role's dashboard.",
    fix: "Check the login journey, role mapping, route security rules and post-login redirect for this profile.",
  },
  "PAGE-007": {
    category: "page",
    severity: "major",
    title: "Page-specific contract is present",
    expected: "The page contains the required landmark, form or primary action defined in its page contract.",
    fix: "Restore the missing page-specific element or update the contract if the product requirement intentionally changed.",
  },
  "ELEMENT-001": {
    category: "element",
    severity: "major",
    title: "Interactive controls have accessible names",
    expected: "Every visible link, button and form control exposes a meaningful accessible name.",
    fix: "Add visible text, an associated <label>, or a precise aria-label; do not label controls with icons alone.",
  },
  "ELEMENT-002": {
    category: "element",
    severity: "major",
    title: "Form fields have labels",
    expected: "Every visible input, select and textarea has a programmatically associated label.",
    fix: "Connect a visible <label> using for/id, or use aria-labelledby where a visible label already exists.",
  },
  "ELEMENT-003": {
    category: "element",
    severity: "major",
    title: "Images define alternative text",
    expected: "Every image has an alt attribute; decorative images use alt=\"\".",
    fix: "Add concise alternative text for meaningful images or an empty alt attribute for decorative images.",
  },
  "ELEMENT-004": {
    category: "element",
    severity: "major",
    title: "Element IDs are unique",
    expected: "No rendered page contains duplicate id values.",
    fix: "Give repeated components unique IDs and update their labels, ARIA references and JavaScript selectors.",
  },
  "ELEMENT-005": {
    category: "element",
    severity: "major",
    title: "Links have valid destinations",
    expected: "Links point to a route, external URL or an existing in-page anchor; javascript: and empty placeholders are not used.",
    fix: "Replace the placeholder with the intended route/button behaviour, or remove the control until it is functional.",
  },
  "ELEMENT-006": {
    category: "element",
    severity: "major",
    title: "Images and media load",
    expected: "Visible images complete successfully and have usable intrinsic dimensions.",
    fix: "Correct the asset path, provide the missing asset and retain width/height or aspect-ratio to prevent layout shift.",
  },
  "ELEMENT-007": {
    category: "element",
    severity: "minor",
    title: "Heading order is logical",
    expected: "Heading levels do not skip levels when introducing nested content.",
    fix: "Use headings to describe document structure and change visual size through CSS rather than skipping levels.",
  },
  "DESIGN-001": {
    category: "design",
    severity: "major",
    title: "Layout has no horizontal overflow",
    expected: "The page fits the selected viewport without unintended horizontal scrolling or off-screen content.",
    fix: "Constrain the reported element, allow wrapping, and check fixed widths, transforms, grids and positioned content at this breakpoint.",
  },
  "DESIGN-002": {
    category: "design",
    severity: "minor",
    title: "Touch targets meet WCAG 2.2 sizing",
    expected: "Non-inline interactive targets on mobile are at least 24 by 24 CSS pixels.",
    fix: "Increase the control's hit area with padding or spacing while keeping the visual hierarchy compact.",
  },
  "DESIGN-003": {
    category: "design",
    severity: "minor",
    title: "Visible text remains readable",
    expected: "Visible interface text is at least 12 CSS pixels and is not clipped to zero width or height.",
    fix: "Increase the font size or remove the layout constraint that clips the text; body copy should normally be 16px or larger.",
  },
  "A11Y-001": {
    category: "accessibility",
    severity: "major",
    title: "WCAG automated rules pass",
    expected: "Axe reports no serious or critical WCAG 2.0/2.1 A or AA violations.",
    fix: "Apply the Axe guidance reported for the affected nodes, then verify the result with keyboard and screen-reader testing.",
  },
  "TEXT-001": {
    category: "text",
    severity: "major",
    title: "Text encoding is clean",
    expected: "Visible copy contains no mojibake or corrupted punctuation characters.",
    fix: "Save the source as UTF-8 and replace the corrupted characters with the intended punctuation or symbol.",
  },
  "TEXT-002": {
    category: "text",
    severity: "major",
    title: "No unfinished placeholder copy",
    expected: "User-facing copy contains no Lorem ipsum, TODO, FIXME, TBD or generic coming-soon placeholders.",
    fix: "Replace the placeholder with final product copy or remove the unfinished surface from the user journey.",
  },
  "TEXT-003": {
    category: "text",
    severity: "minor",
    title: "Headings contain useful text",
    expected: "Visible headings are non-empty and describe the section that follows.",
    fix: "Add a concise descriptive heading or remove the empty heading element.",
  },
  "TEXT-004": {
    category: "text",
    severity: "minor",
    title: "Public copy uses British English",
    expected: "Public-facing prose uses British spellings such as colour, organise, behaviour, centre and optimisation.",
    fix: "Replace the reported American spelling with the British English equivalent, except where it is a code/API or proper name.",
  },
  "RUNTIME-001": {
    category: "runtime",
    severity: "major",
    title: "Browser console is clean",
    expected: "The journey produces no uncaught browser errors.",
    fix: "Trace the reported console error to its JavaScript or failed dependency and handle the underlying error.",
  },
  "RUNTIME-002": {
    category: "runtime",
    severity: "major",
    title: "Required network requests succeed",
    expected: "No same-origin script, stylesheet, image, document or API request fails during the page journey.",
    fix: "Repair the request URL or server response, or handle an optional request without leaving a broken user-facing state.",
  },
};

const commonAuthenticatedPages = [
  { label: "profile", path: "/profile", required: ["main", "h1"] },
  { label: "calendar", path: "/calendar?view=month", required: ["main", "h1"] },
  { label: "inbox", path: "/inbox", required: ["main", "h1"] },
  { label: "support", path: "/support", required: ["main", "form"] },
];

export const profiles = [
  {
    id: "public",
    pages: [
      { label: "home", path: "/", metadata: true, required: ["main", "h1", "nav"] },
      { label: "about", path: "/about", metadata: true, required: ["main", "h1"] },
      { label: "faq", path: "/faq", metadata: true, required: ["main", "h1"] },
      { label: "pricing", path: "/pricing", metadata: true, required: ["main", "h1"] },
      { label: "explore", path: "/explore", metadata: true, required: ["main", "h1"] },
      { label: "merchandise", path: "/merch", metadata: true, required: ["main", "h1"] },
      { label: "login", path: "/login", required: ["#loginForm", "input[type='password']", "button[type='submit']"] },
      { label: "sign-up", path: "/signup", required: ["main", "h1"] },
      { label: "forgot-password", path: "/forgot-password", required: ["main", "form"] },
      { label: "privacy", path: "/policies/privacy", metadata: true, required: ["main", "h1"] },
      { label: "terms", path: "/policies/terms", metadata: true, required: ["main", "h1"] },
      { label: "payments-policy", path: "/policies/payments", metadata: true, required: ["main", "h1"] },
    ],
  },
  {
    id: "client",
    username: "demo_client",
    role: "client",
    homePath: "/dashboard",
    pages: [
      { label: "dashboard", path: "/dashboard", required: ["main", "h1"] },
      ...commonAuthenticatedPages,
      { label: "trainer-marketplace", path: "/client/trainers", required: ["main", "h1"] },
      { label: "goals", path: "/goals", required: ["main", "h1"] },
      { label: "workouts", path: "/workout-management", required: ["main", "h1"] },
      { label: "preferences", path: "/select-preferences", required: ["main", "form"] },
      { label: "achievements", path: "/achievements", required: ["main", "h1"] },
      { label: "health-records", path: "/health-record", required: ["main", "h1"] },
      { label: "blood-pressure", path: "/health/blood-pressure", required: ["main", "h1"] },
      { label: "vault", path: "/vault", required: ["main", "h1"] },
    ],
  },
  {
    id: "trainer",
    username: "demo_trainer",
    role: "trainer",
    homePath: "/trainer/dashboard",
    pages: [
      { label: "dashboard", path: "/trainer/dashboard", required: ["main", "h1"] },
      ...commonAuthenticatedPages,
      { label: "clients", path: "/trainer/clients", required: ["main", "h1"] },
      { label: "library", path: "/trainer/library", required: ["main", "h1"] },
      { label: "exercises", path: "/trainer/library/exercises", required: ["main", "h1"] },
      { label: "workout-templates", path: "/workout-templates", required: ["main", "h1"] },
      { label: "schedules", path: "/schedules", required: ["main", "h1"] },
      { label: "workouts", path: "/workouts", required: ["main", "h1"] },
    ],
  },
  {
    id: "gym",
    username: "demo_gym",
    role: "gym",
    homePath: "/gym/dashboard",
    pages: [
      { label: "dashboard", path: "/gym/dashboard", required: ["main", "h1"] },
      ...commonAuthenticatedPages,
      { label: "trainers", path: "/gym/admin/trainers", required: ["main", "h1"] },
      { label: "memberships", path: "/gym/admin/memberships", required: ["main", "h1"] },
    ],
  },
  {
    id: "admin",
    username: "demo_admin",
    role: "admin",
    homePath: "/admin/dashboard",
    pages: [
      { label: "dashboard", path: "/admin/dashboard", required: ["main", "h1"] },
      ...commonAuthenticatedPages,
      { label: "feedback", path: "/admin/feedback", required: ["main", "h1"] },
      { label: "gym-applications", path: "/admin/gym-applications", required: ["main", "h1"] },
      { label: "merchandise", path: "/admin/merch", required: ["main", "h1"] },
    ],
  },
  {
    id: "super-admin",
    username: "superadmin_demo",
    role: "super-admin",
    homePath: "/admin/dashboard",
    pages: [
      { label: "dashboard", path: "/admin/dashboard", required: ["main", "h1"] },
      { label: "verification-queue", path: "/super-admin/verification/queue", required: ["main", "h1"] },
      ...commonAuthenticatedPages,
    ],
  },
];

export const britishEnglish = new Map([
  ["behavior", "behaviour"],
  ["behaviors", "behaviours"],
  ["color", "colour"],
  ["colors", "colours"],
  ["organize", "organise"],
  ["organized", "organised"],
  ["organizing", "organising"],
  ["optimize", "optimise"],
  ["optimized", "optimised"],
  ["optimization", "optimisation"],
]);
